# Generated by Django 5.0.7 on 2024-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-brand'],
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('extra_options', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField()),
                ('diagonal', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product')),
            ],
        ),
        migrations.CreateModel(
            name='WatchSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('material', models.CharField(max_length=255)),
                ('connectivity', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('car_spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suve_main.carspecs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product')),
                ('storage_spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suve_main.storagespecs')),
                ('watch_spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suve_main.watchspecs')),
            ],
        ),
    ]
