# Generated by Django 5.0.7 on 2024-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespecs',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
