# Generated by Django 5.0.7 on 2024-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0002_alter_storagespecs_diagonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagespecs',
            old_name='storage',
            new_name='rom',
        ),
        migrations.AddField(
            model_name='storagespecs',
            name='cpu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
