# Generated by Django 5.0.7 on 2024-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0004_storagespecs_ram_alter_productprice_car_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='extra_options',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
