# Generated by Django 5.0.7 on 2024-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0005_alter_carspecs_extra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespecs',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
