# Generated by Django 5.0.7 on 2024-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0006_storagespecs_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespecs',
            name='diagonal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
