# Generated by Django 5.0.7 on 2024-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0007_alter_storagespecs_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
