# Generated by Django 5.0.7 on 2024-07-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0010_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product')),
            ],
        ),
    ]
