# Generated by Django 5.0.7 on 2024-08-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0012_alter_productphoto_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='EMAIL')),
                ('password', models.CharField(max_length=255, verbose_name='PASSWORD')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='TIME')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Login',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='carspecs',
            options={'verbose_name': 'Car Spec', 'verbose_name_plural': 'Car Specs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'category'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Product Photo', 'verbose_name_plural': 'Product Photo'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'ordering': ['id'], 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='storagespecs',
            options={'verbose_name': 'Storage Spec', 'verbose_name_plural': 'Storage Specs'},
        ),
        migrations.AlterModelOptions(
            name='watchspecs',
            options={'verbose_name': 'Watch Spec', 'verbose_name_plural': 'Watch Specs'},
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='extra_options',
            field=models.BooleanField(blank=True, null=True, verbose_name='EXTRA OPTIONS'),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product', verbose_name='PRODUCT'),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='type',
            field=models.CharField(max_length=255, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='BRAND'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='PRODUCT NAME'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='PHOTO'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suve_main.product', verbose_name='PRODUCT'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='car_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_spec', to='suve_main.carspecs', verbose_name='CAR SPEC ID'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product', verbose_name='PRODUCT'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='storage_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_spec', to='suve_main.storagespecs', verbose_name='STORAGE SPEC ID'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='watch_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_spec', to='suve_main.watchspecs', verbose_name='WATCH SPEC ID'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='diagonal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GPU'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product', verbose_name='PRODUCT'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='rom',
            field=models.IntegerField(verbose_name='ROM'),
        ),
        migrations.AlterField(
            model_name='watchspecs',
            name='connectivity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CONNECTIVITY'),
        ),
        migrations.AlterField(
            model_name='watchspecs',
            name='material',
            field=models.CharField(max_length=255, verbose_name='MATERIAL'),
        ),
        migrations.AlterField(
            model_name='watchspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suve_main.product', verbose_name='PRODUCT'),
        ),
        migrations.AlterField(
            model_name='watchspecs',
            name='size',
            field=models.IntegerField(verbose_name='SIZE'),
        ),
    ]
