# Generated by Django 5.0.7 on 2024-08-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0013_login_alter_carspecs_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
