# Generated by Django 5.0.7 on 2024-09-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suve_main', '0014_alter_login_date_alter_login_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
